Repository input-output-hk/chain-wallet-libs, pull requests merged in 2020-04, with the labels that each got.

#20 Fix the wallet-c tests by moving them down to the underlying Wallet crate
  .github/workflows/ci_checks.yaml
  wallet-c/tests/daedalus1.rs
  wallet-c/tests/yoroi1.rs
  wallet/Cargo.toml
  wallet/tests/daedalus1.rs
  wallet/tests/yoroi1.rs
Labels: bug

#26 try to recover paperwallet
  wallet-c/src/lib.rs
  wallet-js/src/lib.rs
  wallet/src/password.rs
  wallet/src/recovering/mod.rs
  wallet/src/recovering/paperwallet.rs
  wallet/tests/paperwallet1.rs
Labels: enhancement

#30 Transaction builder
  hdkeygen/src/account.rs
  wallet-c/src/lib.rs
  wallet-js/src/lib.rs
  wallet/src/blockchain.rs
  wallet/src/lib.rs
  wallet/src/recovering/mod.rs
  wallet/src/transaction/builder.rs
  wallet/src/transaction/dump.rs
  wallet/src/transaction/input_selection.rs
  wallet/src/transaction/mod.rs
  wallet/src/transaction/witness_builder.rs
Labels: enhancement

#32 Update readme
  README.md
Labels: documentation

#33 Release ci fix
  .github/workflows/release.yaml
Labels: CI/CD, bug

#34 Removed old android release script
  .github/workflows/ci_android_release.yaml
Labels: CI/CD

#36 add cordova android plugin
  .github/workflows/release.yaml
  bindings/wallet-cordova/.gitattributes
  bindings/wallet-cordova/.gitignore
  bindings/wallet-cordova/.npmignore
  bindings/wallet-cordova/LICENSE-APACHE
  bindings/wallet-cordova/LICENSE-MIT
  bindings/wallet-cordova/README.md
  bindings/wallet-cordova/package.json
  bindings/wallet-cordova/plugin.xml
  bindings/wallet-cordova/src/android/WalletPlugin.java
  bindings/wallet-cordova/src/android/jormungandrwallet/Settings.java
  bindings/wallet-cordova/src/android/jormungandrwallet/Wallet.java
  bindings/wallet-cordova/src/browser/Wallet.js
  bindings/wallet-cordova/src/osx/Wallet.h
  bindings/wallet-cordova/src/osx/Wallet.m
  bindings/wallet-cordova/src/windows/Wallet.js
  bindings/wallet-cordova/tests/package.json
  bindings/wallet-cordova/tests/plugin.xml
  bindings/wallet-cordova/tests/tests.js
  bindings/wallet-cordova/www/wallet.js
Labels: VOTE, bindings - cordova

#39 add some cleanup in the API toinclude better error reporting
  bindings/wallet-c/cbingden.toml
  bindings/wallet-c/regen_header.sh
  bindings/wallet-c/src/lib.rs
  bindings/wallet-c/wallet.h
  bindings/wallet-core/Cargo.toml
  bindings/wallet-core/src/c.rs
  bindings/wallet-core/src/conversion.rs
  bindings/wallet-core/src/error.rs
  bindings/wallet-core/src/lib.rs
  bindings/wallet-core/src/wallet.rs
  bindings/wallet-jni/src/lib.rs
  bindings/wallet-js/Cargo.toml
  bindings/wallet-js/src/lib.rs
Labels: VOTE, cleanup, enhancement

#42 Retrieve funds single iteration
  bindings/wallet-core/src/wallet.rs
  wallet/src/recovering/daedalus.rs
  wallet/src/recovering/icarus.rs
Labels: enhancement

#44 Expose settings data
  bindings/wallet-core/src/wallet.rs
  wallet/Cargo.toml
  wallet/src/blockchain.rs
Labels: VOTE, enhancement

#48 Add electron plugin impl
  bindings/wallet-cordova/.gitignore
  bindings/wallet-cordova/BUILD.md
  bindings/wallet-cordova/README.md
  bindings/wallet-cordova/TESTING.md
  bindings/wallet-cordova/build_wasm.py
  bindings/wallet-cordova/plugin.xml
  bindings/wallet-cordova/src/electron/walletProxy.js
Labels: VOTE, bindings - cordova

#46 Move inputs to ignored if mk_output fails for build_tx_and_clear
  wallet/src/transaction/dump.rs
Labels: bug
