Repository input-output-hk/chain-wallet-libs, pull requests merged in 2020-08, with the labels that each got.

#89 add transfer protocol de-encrypt
  Cargo.toml
  bindings/wallet-android/.project
  bindings/wallet-c/src/lib.rs
  bindings/wallet-c/wallet.h
  bindings/wallet-cordova/plugin.xml
  bindings/wallet-cordova/src/android/WalletPlugin.java
  bindings/wallet-cordova/tests/tests.js
  bindings/wallet-cordova/www/wallet.js
  bindings/wallet-core/Cargo.toml
  bindings/wallet-core/src/c.rs
  bindings/wallet-core/src/error.rs
  bindings/wallet-jni/java/WalletTest.java
  bindings/wallet-jni/java/com/iohk/jormungandrwallet/SymmetricCipher.java
  bindings/wallet-jni/java/run_test.py
  bindings/wallet-jni/src/lib.rs
  hdkeygen/src/account.rs
  symmetric-cipher/Cargo.toml
  symmetric-cipher/src/lib.rs
  wallet/Cargo.toml
Labels: enhancement

#92 Update bip44 doctest
  chain-path-derivation/src/bip44.rs
  wallet/tests/account.rs
  wallet/tests/daedalus.rs
  wallet/tests/yoroi.rs
Labels: cleanup

#95 wallet.h - regen
  bindings/wallet-c/src/lib.rs
  bindings/wallet-c/wallet.h
Labels: bindings - c, bug

#99 fix decryption test case
  bindings/wallet-cordova/tests/tests.js
Labels: bindings - cordova, tests

#100 add decryption authentication check
  bindings/wallet-core/src/c.rs
  bindings/wallet-core/src/error.rs
  bindings/wallet-jni/java/WalletTest.java
  symmetric-cipher/src/lib.rs
Labels: bug
