Repository input-output-hk/chain-wallet-libs, pull requests merged in 2021-07, with the labels that each got.

#159 Update to chain libs 271e6f00
  bindings/wallet-core/src/c/vote.rs
  bindings/wallet-core/src/vote.rs
  bindings/wallet-core/src/wallet.rs
  bindings/wallet-jni/java/WalletTest.java
  bindings/wallet-js/src/lib.rs
  doc/getting_started.md
  hdkeygen/Cargo.toml
  test-vectors/daedalus/wallet2.json
  wallet/Cargo.toml
  wallet/src/recovering/mod.rs
  wallet/src/transaction/dump.rs
  wallet/tests/daedalus.rs
  wallet/tests/free_keys.rs
  wallet/tests/paperwallet1.rs
Labels: dependencies

#162 Small fixes in wallet bindings API and code
  bindings/wallet-c/src/lib.rs
  bindings/wallet-js/src/lib.rs
  wallet/src/scheme/freeutxo.rs
Labels: bindings - c, bindings - js, cleanup

#165 Clippy 0.1.54 fixes
  bindings/wallet-core/src/c/mod.rs
  bindings/wallet-js/src/lib.rs
  symmetric-cipher/src/lib.rs
  wallet/src/scheme/bip44.rs
  wallet/src/transaction/dump.rs
Labels: cleanup
