Repository input-output-hk/chain-wallet-libs, pull requests merged in 2021-01, with the labels that each got.

#132 regen header with cbindgen 0.16.0
  bindings/wallet-c/wallet.h
Labels: bindings - c

#130 Use official upload release asset
  .github/workflows/release.yaml
Labels: CI/CD

#131 Fix cargo and clippy warnings
  bindings/wallet-jni/src/lib.rs
  bindings/wallet-js/Cargo.toml
  chain-path-derivation/src/derivation.rs
  keygen/Cargo.toml
Labels: cleanup

#133 run apt update before apt install
  .github/workflows/ci_checks.yaml
Labels: CI/CD, bindings - jni

#135 reintroduce decryption function in wallet-js
  bindings/wallet-js/src/lib.rs
Labels: bug
