Repository input-output-hk/chain-wallet-libs, pull requests merged in 2021-09, with the labels that each got.

#183 don't upload artifacts on integration
  .github/workflows/ci_integration.yaml
Labels: CI/CD

#185 0.7.0-pre4: add changelog entry
  CHANGELOG.md
Labels: documentation

#166 re-implement States with hashlink
  hdkeygen/src/rindex/hdpayload.rs
  wallet/Cargo.toml
  wallet/src/account.rs
  wallet/src/scheme/bip44.rs
  wallet/src/scheme/freeutxo.rs
  wallet/src/scheme/rindex.rs
  wallet/src/states.rs
Labels: enhancement, dependencies

#190 CI: Use actions-rs/install to install cbindgen
  .github/workflows/ci_checks.yaml
Labels: CI/CD
