Repository input-output-hk/chain-wallet-libs, pull requests merged in 2021-05, with the labels that each got.

#150 Fix to payload and clippy issues
  bindings/wallet-core/src/c/vote.rs
  bindings/wallet-core/src/vote.rs
  hdkeygen/src/account.rs
  hdkeygen/src/rindex/hdpayload.rs
  symmetric-cipher/src/lib.rs
  wallet/src/store/utxo.rs
Labels: cleanup

#152 fix invalid account funds tracking
  bindings/wallet-core/src/error.rs
  bindings/wallet-core/src/wallet.rs
  wallet/src/account.rs
  wallet/src/states.rs
  wallet/tests/account.rs
  wallet/tests/free_keys.rs
  wallet/tests/utils/mod.rs
Labels: bug

#153 Add fragment id from raw
  CHANGELOG.md
  bindings/wallet-c/src/lib.rs
  bindings/wallet-c/wallet.h
  bindings/wallet-cordova/build_jni.py
  bindings/wallet-cordova/plugin.xml
  bindings/wallet-cordova/src/android/WalletPlugin.java
  bindings/wallet-cordova/src/ios/WalletPlugin.h
  bindings/wallet-cordova/src/ios/WalletPlugin.m
  bindings/wallet-cordova/tests/src/main.js
  bindings/wallet-cordova/www/wallet.js
  bindings/wallet-core/src/c/fragment.rs
  bindings/wallet-core/src/c/mod.rs
  bindings/wallet-core/src/error.rs
  bindings/wallet-core/src/lib.rs
  bindings/wallet-core/src/wallet.rs
  bindings/wallet-jni/java/WalletTest.java
  bindings/wallet-jni/java/com/iohk/jormungandrwallet/Fragment.java
  bindings/wallet-jni/src/lib.rs
Labels: bindings - cordova, bindings - jni, enhancement

#157 ci: check python scripts with black
  .github/workflows/python-scripts.yml
  bindings/wallet-android/src/main/jniLibs/rename_targets.py
  bindings/wallet-cordova/build_ios.py
  bindings/wallet-cordova/build_jni.py
  bindings/wallet-cordova/build_wasm.py
  bindings/wallet-cordova/copy_jni_definitions.py
  bindings/wallet-jni/java/run_test.py
Labels: CI/CD
